from pathlib import Path
from typing import Optional
import shutil
import markdown


class HTMLReportRenderer:
    """
    Markdown → HTML renderer (v3.6)

    - Executive-grade HTML theme
    - Visual evidence preserved (visuals/)
    - HTML is canonical output
    - PDF-safe (Chromium / Browserless compatible)
    """

    def render(
        self,
        md_path: Path,
        output_dir: Optional[Path] = None,
    ) -> Path:
        md_path = Path(md_path)
        if not md_path.exists():
            raise FileNotFoundError(f"Markdown file not found: {md_path}")

        # HTML output directory
        output_dir = Path(output_dir or md_path.parent)
        output_dir.mkdir(parents=True, exist_ok=True)

        html_path = output_dir / md_path.with_suffix(".html").name

        # -------------------------------------------------
        # Markdown → HTML
        # -------------------------------------------------
        md_text = md_path.read_text(encoding="utf-8")

        html_body = markdown.markdown(
            md_text,
            extensions=["tables", "fenced_code"],
        )

        # -------------------------------------------------
        # Preserve visuals/ directory (CRITICAL)
        # -------------------------------------------------
        visuals_src = md_path.parent / "visuals"
        visuals_dst = output_dir / "visuals"

        if visuals_src.exists() and visuals_src.is_dir():
            visuals_dst.mkdir(exist_ok=True)

            for img in visuals_src.glob("*"):
                target = visuals_dst / img.name
                if not target.exists():
                    shutil.copy(img, target)

        # -------------------------------------------------
        # BASE HREF (🔥 THIS FIXES PDF IMAGES 🔥)
        # -------------------------------------------------
        base_href = output_dir.resolve().as_uri() + "/"

        # -------------------------------------------------
        # Executive HTML + CSS Theme
        # -------------------------------------------------
        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<base href="{base_href}">
<title>Sreejita Executive Report</title>

<style>
:root {{
  --bg: #ffffff;
  --text: #1f2937;
  --muted: #6b7280;
  --primary: #0f172a;
  --border: #e5e7eb;

  --info: #2563eb;
  --warning: #d97706;
  --risk: #b91c1c;
}}

body {{
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Arial, sans-serif;
  background: var(--bg);
  color: var(--text);
  margin: 0;
  padding: 40px;
}}

.report {{
  max-width: 1100px;
  margin: 0 auto;
}}

h1 {{
  font-size: 28px;
  margin-bottom: 8px;
  color: var(--primary);
}}

h2 {{
  font-size: 20px;
  margin-top: 40px;
  margin-bottom: 16px;
  color: var(--primary);
  border-left: 4px solid var(--primary);
  padding-left: 12px;
}}

h3 {{
  font-size: 16px;
  margin-top: 24px;
  color: var(--primary);
}}

p {{
  line-height: 1.6;
  font-size: 15px;
}}

hr {{
  border: none;
  border-top: 1px solid var(--border);
  margin: 32px 0;
}}

table {{
  width: 100%;
  border-collapse: collapse;
  margin-top: 16px;
  font-size: 14px;
}}

th, td {{
  border: 1px solid var(--border);
  padding: 8px 10px;
}}

th {{
  background: #f9fafb;
  text-align: left;
}}

blockquote {{
  background: #f9fafb;
  border-left: 4px solid var(--info);
  padding: 12px 16px;
  margin: 20px 0;
  color: #374151;
}}

img {{
  max-width: 100%;
  border: 1px solid var(--border);
  border-radius: 4px;
  margin: 12px 0;
}}

.report-footer {{
  margin-top: 48px;
  padding-top: 16px;
  border-top: 1px solid var(--border);
  font-size: 12px;
  color: var(--muted);
  text-align: center;
}}
</style>
</head>

<body>
  <div class="report">
    {html_body}

    <div class="report-footer">
      Generated by <strong>Sreejita Framework</strong> · v3.6 · Confidential
    </div>
  </div>
</body>
</html>
"""

        html_path.write_text(html, encoding="utf-8")
        return html_path
