from pathlib import Path
from typing import Optional
import shutil
import markdown
import re


class HTMLReportRenderer:
    """
    Markdown → HTML renderer (v3.6.1 – HARDENED)

    GUARANTEES:
    - HTML always written OR exception raised
    - visuals/ copied OR exception raised
    - Markdown image references validated
    """

    IMG_MD_REGEX = re.compile(r'!\[.*?\]\((.*?)\)')

    def render(
        self,
        md_path: Path,
        output_dir: Optional[Path] = None,
    ) -> Path:
        md_path = Path(md_path)
        if not md_path.exists():
            raise FileNotFoundError(f"Markdown file not found: {md_path}")

        output_dir = Path(output_dir or md_path.parent)
        output_dir.mkdir(parents=True, exist_ok=True)

        html_path = output_dir / md_path.with_suffix(".html").name

        # -------------------------------------------------
        # READ MARKDOWN
        # -------------------------------------------------
        md_text = md_path.read_text(encoding="utf-8")

        # -------------------------------------------------
        # FIND IMAGE REFERENCES IN MARKDOWN
        # -------------------------------------------------
        referenced_images = self.IMG_MD_REGEX.findall(md_text)

        # -------------------------------------------------
        # CONVERT MARKDOWN → HTML
        # -------------------------------------------------
        html_body = markdown.markdown(
            md_text,
            extensions=["tables", "fenced_code"],
        )

        # -------------------------------------------------
        # VISUALS CONTRACT (HARD RULE)
        # -------------------------------------------------
        visuals_src = md_path.parent / "visuals"
        visuals_dst = output_dir / "visuals"

        if referenced_images:
            if not visuals_src.exists():
                raise RuntimeError(
                    "Markdown references visuals but visuals/ directory is missing"
                )

            visuals_dst.mkdir(exist_ok=True)

            copied = []
            for img in visuals_src.glob("*"):
                target = visuals_dst / img.name
                if not target.exists():
                    shutil.copy(img, target)
                copied.append(target.name)

            # Validate references
            for ref in referenced_images:
                ref_name = Path(ref).name
                if ref_name not in copied:
                    raise RuntimeError(
                        f"Referenced image '{ref_name}' not found in visuals/"
                    )

        # -------------------------------------------------
        # BASE HREF (CRITICAL FOR PDF / BROWSERLESS)
        # -------------------------------------------------
        base_href = output_dir.resolve().as_uri() + "/"

        # -------------------------------------------------
        # EXECUTIVE HTML
        # -------------------------------------------------
        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<base href="{base_href}">
<title>Sreejita Executive Report</title>

<style>
body {{
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Arial, sans-serif;
  background: #ffffff;
  color: #1f2937;
  margin: 0;
  padding: 40px;
}}
.report {{
  max-width: 1100px;
  margin: 0 auto;
}}
img {{
  max-width: 100%;
  border: 1px solid #e5e7eb;
  margin: 12px 0;
}}
</style>
</head>

<body>
  <div class="report">
    {html_body}
    <hr>
    <div style="font-size:12px;color:#6b7280;text-align:center;">
      Generated by <strong>Sreejita Framework</strong> · v3.6 · Confidential
    </div>
  </div>
</body>
</html>
"""

        html_path.write_text(html, encoding="utf-8")

        # -------------------------------------------------
        # FINAL GUARANTEE
        # -------------------------------------------------
        if not html_path.exists():
            raise RuntimeError("HTML generation failed — file not written")

        return html_path
