from datetime import datetime
from pathlib import Path
from typing import Optional

import pandas as pd
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    PageBreak,
    Image,
    Table,
    TableStyle,
)

from sreejita.reporting.orchestrator import generate_report_payload
from sreejita.domains.router_dispatch import dispatch_domain
from sreejita.policy.engine import PolicyEngine
from sreejita.core.cleaner import clean_dataframe


# =====================================================
# HEADER / FOOTER
# =====================================================

def header_footer(canvas, doc):
    canvas.saveState()
    canvas.setFont("Helvetica", 9)

    if doc.page > 1:
        canvas.drawString(
            2 * cm,
            A4[1] - 1.2 * cm,
            "Sreejita Framework – Hybrid Decision Intelligence Report"
        )

    canvas.drawRightString(
        A4[0] - 2 * cm,
        1.2 * cm,
        f"Generated by Sreejita Data Labs · {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}"
    )
    canvas.restoreState()


# =====================================================
# VALUE FORMATTER
# =====================================================

def format_value(value):
    if value is None:
        return "N/A"

    if isinstance(value, (int, float)):
        abs_val = abs(value)

        if abs_val >= 1_000_000:
            return f"{value / 1_000_000:.2f}M"
        if abs_val >= 1_000:
            return f"{value / 1_000:.1f}K"
        if 0 < abs_val < 1:
            return f"{value:.1%}"

        return f"{value:,.2f}"

    return str(value)


# =====================================================
# HYBRID REPORT
# =====================================================

def run(input_path: str, config: dict, output_path: Optional[str] = None) -> str:
    input_path = Path(input_path)

    if output_path is None:
        out_dir = input_path.parent / "reports"
        out_dir.mkdir(exist_ok=True)
        output_path = out_dir / f"Hybrid_Report_{datetime.utcnow().strftime('%Y%m%d_%H%M%S')}.pdf"

    # --- FIX 1: Safe Encoding Fallback ---
    try:
        df_raw = pd.read_csv(input_path, encoding="utf-8")
    except UnicodeDecodeError:
        df_raw = pd.read_csv(input_path, encoding="latin1")

    df = clean_dataframe(df_raw)["df"]

    # Domain decision + policy
    decision = dispatch_domain(df)
    policy = PolicyEngine(min_confidence=0.7).evaluate(decision)

    payload = generate_report_payload(df, decision, policy)

    kpis = payload.get("kpis", {})
    insights = payload.get("insights", [])
    recommendations = payload.get("recommendations", [])
    visuals = payload.get("visuals", [])

    styles = getSampleStyleSheet()

    brand = ParagraphStyle(
        "brand",
        parent=styles["Title"],
        alignment=1,
        fontSize=26,
        spaceAfter=6,
    )

    tagline = ParagraphStyle(
        "tagline",
        parent=styles["Normal"],
        alignment=1,
        fontSize=14,
        textColor="#555555",
        spaceAfter=18,
    )

    h1 = ParagraphStyle("h1", parent=styles["Heading1"])
    h2 = ParagraphStyle("h2", parent=styles["Heading2"])
    body = styles["BodyText"]

    doc = SimpleDocTemplate(
        str(output_path),
        pagesize=A4,
        leftMargin=2 * cm,
        rightMargin=2 * cm,
        topMargin=3 * cm,
        bottomMargin=2 * cm,
    )

    story = []

    # =====================================================
    # PAGE 1 — EXECUTIVE BRIEF
    # =====================================================

    story.append(Paragraph("Sreejita Data Labs", brand))
    story.append(Paragraph("Insights · Intelligence · Impact", tagline))

    story.append(Paragraph("EXECUTIVE BRIEF (1-MINUTE READ)", h2))
    story.append(Paragraph(f"Detected Domain: <b>{decision.selected_domain}</b>", body))
    story.append(Paragraph(f"Policy Status: <b>{policy.status}</b>", body))

    warning_count = sum(1 for i in insights if i.get("level") == "WARNING")
    risk_count = sum(1 for i in insights if i.get("level") == "RISK")

    story.append(Paragraph(
        f"Issues Identified: {warning_count} Warning(s), {risk_count} Risk(s)",
        body
    ))

    if recommendations:
        story.append(Paragraph(
            f"Immediate Focus: <b>{recommendations[0].get('action','')}</b>",
            body
        ))

    story.append(Spacer(1, 14))

    # =====================================================
    # KPI SNAPSHOT
    # =====================================================

    snapshot_rows = [["Metric", "Value"]]
    for k, v in kpis.items():
        snapshot_rows.append([k.replace("_", " ").title(), format_value(v)])

    if len(snapshot_rows) == 1:
        snapshot_rows.append(["KPIs", "Not Available"])

    table = Table(snapshot_rows, colWidths=[9 * cm, 5 * cm])
    table.setStyle(TableStyle([
        ("GRID", (0, 0), (-1, -1), 0.5, "#999999"),
        ("BACKGROUND", (0, 0), (-1, 0), "#EEEEEE"),
    ]))

    story.append(table)
    story.append(PageBreak())

    # =====================================================
    # VISUAL EVIDENCE (FIXED PAGINATION)
    # =====================================================

    if visuals:
        story.append(Paragraph("Visual Evidence", h1))
        story.append(Spacer(1, 12))

        VISUALS_PER_PAGE = 2

        for idx, v in enumerate(visuals):
            # --- FIX 2: Aspect Ratio Safety ---
            # preserveAspectRatio=True prevents square charts from stretching
            story.append(Image(
                str(v["path"]), 
                width=14 * cm, 
                height=8 * cm, 
                ))
            story.append(Paragraph(v.get("caption", ""), body))
            
            # --- FIX 3: The "Blank Page" Fix ---
            # Only add Spacer if it's NOT the last image.
            # This prevents a stray spacer from pushing to a new blank page.
            if idx < len(visuals) - 1:
                story.append(Spacer(1, 14))

            # Dynamic Page Break
            # Note: We check idx+1 < len so we don't break on the very last item loop
            if (idx + 1) % VISUALS_PER_PAGE == 0 and idx + 1 < len(visuals):
                story.append(PageBreak())

        story.append(PageBreak())

    # =====================================================
    # INSIGHTS & RECOMMENDATIONS
    # =====================================================

    story.append(Paragraph("Key Insights", h1))

    if insights:
        for i in insights:
            story.append(Paragraph(
                f"[{i.get('level','INFO')}] {i.get('title','Insight')}",
                body
            ))
            story.append(Paragraph(i.get("so_what",""), body))
            story.append(Spacer(1, 8))
    else:
        story.append(Paragraph(
            "No critical risks were identified. Performance indicators appear stable.",
            body
        ))

    story.append(Spacer(1, 12))
    story.append(Paragraph("Recommendations", h1))

    if recommendations:
        for r in recommendations:
            story.append(Paragraph(f"<b>Action:</b> {r.get('action','')}", body))
            story.append(Paragraph(f"Priority: {r.get('priority','Medium')}", body))
            story.append(Paragraph(f"Timeline: {r.get('timeline','')}", body))
            story.append(Spacer(1, 10))
    else:
        story.append(Paragraph(
            "No immediate corrective actions are recommended.",
            body
        ))

    story.append(PageBreak())

    # =====================================================
    # RISKS
    # =====================================================

    story.append(Paragraph("Risks", h1))
    risks = [i for i in insights if i.get("level") in {"WARNING", "RISK"}]

    if risks:
        for r in risks:
            story.append(Paragraph(r.get("title","Risk"), body))
            story.append(Paragraph(r.get("so_what",""), body))
            story.append(Spacer(1, 8))
    else:
        story.append(Paragraph(
            "No material risks detected.",
            body
        ))

    doc.build(story, onFirstPage=header_footer, onLaterPages=header_footer)
    return str(output_path)
