from datetime import datetime
from pathlib import Path
from typing import Optional

import pandas as pd
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    PageBreak,
    Image,
    Table,
    TableStyle,
)

from sreejita.reporting.orchestrator import generate_report_payload
from sreejita.domains.router_dispatch import dispatch_domain
from sreejita.policy.engine import PolicyEngine
from sreejita.core.cleaner import clean_dataframe


# =====================================================
# HEADER / FOOTER
# =====================================================

def header_footer(canvas, doc):
    canvas.saveState()
    canvas.setFont("Helvetica", 9)

    if doc.page > 1:
        canvas.drawString(
            2 * cm,
            A4[1] - 1.2 * cm,
            "Sreejita Framework – Hybrid Decision Intelligence Report"
        )

    canvas.drawRightString(
        A4[0] - 2 * cm,
        1.2 * cm,
        f"Generated by Sreejita Data Labs · {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}"
    )
    canvas.restoreState()


# =====================================================
# VALUE FORMATTER
# =====================================================

def format_value(value):
    if value is None:
        return "N/A"

    if isinstance(value, (int, float)):
        abs_val = abs(value)
        if abs_val >= 1_000_000:
            return f"{value / 1_000_000:.2f}M"
        if abs_val >= 1_000:
            return f"{value / 1_000:.1f}K"
        if 0 < abs_val < 1:
            return f"{value:.1%}"
        return f"{value:,.2f}"

    return str(value)


# =====================================================
# ROBUST FILE LOADER (CSV + EXCEL)
# =====================================================

def robust_read_dataframe(path: Path) -> pd.DataFrame:
    """
    Robust loader for CSV, XLSX, XLS with real-world mess handling.
    """

    suffix = path.suffix.lower()

    # ---------------- CSV ----------------
    if suffix == ".csv":
        try:
            return pd.read_csv(path, encoding="utf-8")
        except Exception:
            try:
                return pd.read_csv(
                    path,
                    encoding="latin1",
                    engine="python",
                    sep=None,
                    on_bad_lines="skip"
                )
            except Exception as e:
                raise RuntimeError(f"Failed to parse CSV file: {e}")

    # ---------------- EXCEL ----------------
    if suffix in {".xlsx", ".xls"}:
        try:
            xl = pd.ExcelFile(path)
        except Exception as e:
            raise RuntimeError(f"Failed to open Excel file: {e}")

        # Try sheets in order until a valid dataframe is found
        for sheet in xl.sheet_names:
            try:
                df = xl.parse(sheet_name=sheet)
                # Drop fully empty rows/cols
                df = df.dropna(axis=0, how="all").dropna(axis=1, how="all")

                # Require minimal structure
                if df.shape[1] >= 2 and df.shape[0] >= 2:
                    return df
            except Exception:
                continue

        raise RuntimeError(
            "Excel file contains no readable sheets with usable tabular data."
        )

    # ---------------- UNSUPPORTED ----------------
    raise RuntimeError(
        f"Unsupported file type: {suffix}. Only CSV, XLSX, XLS supported."
    )


# =====================================================
# HYBRID REPORT
# =====================================================

def run(input_path: str, config: dict, output_path: Optional[str] = None) -> str:
    input_path = Path(input_path)

    if output_path is None:
        out_dir = input_path.parent / "reports"
        out_dir.mkdir(exist_ok=True)
        output_path = out_dir / f"Hybrid_Report_{datetime.utcnow().strftime('%Y%m%d_%H%M%S')}.pdf"

    # 🔐 Robust ingestion
    df_raw = robust_read_dataframe(input_path)

    # 🔐 Defensive cleaning
    df = clean_dataframe(df_raw)["df"]

    # 🧠 Domain intelligence
    decision = dispatch_domain(df)
    policy = PolicyEngine(min_confidence=0.7).evaluate(decision)
    payload = generate_report_payload(df, decision, policy)

    kpis = payload.get("kpis", {})
    insights = payload.get("insights", [])
    recommendations = payload.get("recommendations", [])
    visuals = payload.get("visuals", [])

    styles = getSampleStyleSheet()
    brand = ParagraphStyle("brand", parent=styles["Title"], alignment=1, fontSize=26)
    tagline = ParagraphStyle("tagline", parent=styles["Normal"], alignment=1, fontSize=14)
    h1 = ParagraphStyle("h1", parent=styles["Heading1"])
    h2 = ParagraphStyle("h2", parent=styles["Heading2"])
    body = styles["BodyText"]

    doc = SimpleDocTemplate(
        str(output_path),
        pagesize=A4,
        leftMargin=2 * cm,
        rightMargin=2 * cm,
        topMargin=3 * cm,
        bottomMargin=2 * cm,
    )

    story = []

    # =====================================================
    # PAGE 1 — EXECUTIVE BRIEF
    # =====================================================

    story.append(Paragraph("Sreejita Data Labs", brand))
    story.append(Paragraph("Insights · Intelligence · Impact", tagline))
    story.append(Paragraph("EXECUTIVE BRIEF (1-MINUTE READ)", h2))
    story.append(Paragraph(f"Detected Domain: <b>{decision.selected_domain}</b>", body))
    story.append(Paragraph(f"Policy Status: <b>{policy.status}</b>", body))

    warning_count = sum(1 for i in insights if i.get("level") == "WARNING")
    risk_count = sum(1 for i in insights if i.get("level") == "RISK")

    story.append(Paragraph(
        f"Issues Identified: {warning_count} Warning(s), {risk_count} Risk(s)",
        body
    ))

    if recommendations:
        story.append(Paragraph(
            f"Immediate Focus: <b>{recommendations[0].get('action','')}</b>",
            body
        ))

    story.append(Spacer(1, 14))

    # =====================================================
    # KPI SNAPSHOT
    # =====================================================

    rows = [["Metric", "Value"]]
    for k, v in kpis.items():
        rows.append([k.replace("_", " ").title(), format_value(v)])

    if len(rows) == 1:
        rows.append(["KPIs", "Not Available"])

    table = Table(rows, colWidths=[9 * cm, 5 * cm])
    table.setStyle(TableStyle([
        ("GRID", (0, 0), (-1, -1), 0.5, "#999999"),
        ("BACKGROUND", (0, 0), (-1, 0), "#EEEEEE"),
    ]))

    story.append(table)
    story.append(PageBreak())

    # =====================================================
    # VISUAL EVIDENCE
    # =====================================================

    story.append(Paragraph("Visual Evidence", h1))

    if not visuals:
        story.append(Paragraph(
            "No defensible visual evidence could be generated from the available data.",
            body
        ))
        story.append(PageBreak())
    else:
        story.append(Spacer(1, 12))
        for v in visuals[:4]:
            story.append(Image(str(v["path"]), width=14 * cm, height=8 * cm))
            story.append(Paragraph(v.get("caption", ""), body))
            story.append(Spacer(1, 14))
        story.append(PageBreak())

    # =====================================================
    # INSIGHTS & RECOMMENDATIONS
    # =====================================================

    story.append(Paragraph("Key Insights", h1))
    for i in insights:
        story.append(Paragraph(f"[{i['level']}] {i['title']}", body))
        story.append(Paragraph(i["so_what"], body))
        story.append(Spacer(1, 8))

    story.append(Paragraph("Recommendations", h1))
    for r in recommendations:
        story.append(Paragraph(f"<b>Action:</b> {r['action']}", body))
        story.append(Paragraph(f"Priority: {r['priority']}", body))
        story.append(Paragraph(f"Timeline: {r['timeline']}", body))
        story.append(Spacer(1, 10))

    doc.build(story, onFirstPage=header_footer, onLaterPages=header_footer)
    return str(output_path)
