from datetime import datetime
from pathlib import Path
from typing import Optional

import pandas as pd
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    PageBreak,
    Image,
    Table,
    TableStyle,
)

from sreejita.reporting.orchestrator import generate_report_payload
from sreejita.domains.router import decide_domain
from sreejita.policy.engine import PolicyEngine
from sreejita.core.cleaner import clean_dataframe
from sreejita.domains.router_dispatch import dispatch_domain

# =====================================================
# HEADER / FOOTER (BRANDING)
# =====================================================

def header_footer(canvas, doc):
    canvas.saveState()
    canvas.setFont("Helvetica", 9)

    if doc.page > 1:
        canvas.drawString(
            2 * cm,
            A4[1] - 1.2 * cm,
            "Sreejita Framework – Hybrid Decision Intelligence Report"
        )

    canvas.drawRightString(
        A4[0] - 2 * cm,
        1.2 * cm,
        f"Generated by Sreejita Data Labs · {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}"
    )
    canvas.restoreState()


# =====================================================
# KPI FORMATTER
# =====================================================

def format_kpi(name, value):
    if value is None:
        return "N/A"

    # Explicit % KPIs
    if name in {
        "profit_margin",
        "target_profit_margin",
        "average_discount",
        "shipping_cost_ratio",
    }:
        return f"{value:.1%}"

    # Currency-like
    if "revenue" in name or "sales" in name or "cost" in name:
        return f"${value:,.2f}"

    # Default
    return str(value)


# =====================================================
# HYBRID REPORT (FINAL v2.x)
# =====================================================

def run(input_path: str, config: dict, output_path: Optional[str] = None) -> str:
    input_path = Path(input_path)

    if output_path is None:
        out_dir = input_path.parent / "reports"
        out_dir.mkdir(exist_ok=True)
        output_path = out_dir / f"Hybrid_Report_{datetime.utcnow().strftime('%Y%m%d_%H%M%S')}.pdf"

    df = clean_dataframe(pd.read_csv(input_path, encoding="latin1"))["df"]

    decision = dispatch_domain(df)
    policy = PolicyEngine(min_confidence=0.7).evaluate(decision)

    payload = generate_report_payload(df, decision, policy)

    # Absolute safety
    if not payload:
        payload = {
            "kpis": {},
            "insights": [],
            "recommendations": [],
            "visuals": [],
        }

    kpis = payload.get("kpis", {})
    insights = payload.get("insights", [])
    recommendations = payload.get("recommendations", [])
    visuals = payload.get("visuals", [])

    styles = getSampleStyleSheet()
    h1 = ParagraphStyle("h1", parent=styles["Heading1"])
    h2 = ParagraphStyle("h2", parent=styles["Heading2"])
    body = styles["BodyText"]

    doc = SimpleDocTemplate(
        str(output_path),
        pagesize=A4,
        leftMargin=2 * cm,
        rightMargin=2 * cm,
        topMargin=3 * cm,
        bottomMargin=2 * cm,
    )

    story = []

    # =====================================================
    # PAGE 1 — EXECUTIVE BRIEF (BRANDED)
    # =====================================================

    story.append(Paragraph(
        "<b>Sreejita Data Labs</b><br/>"
        "<i>Insights · Intelligence · Impact</i>",
        h1
    ))
    story.append(Spacer(1, 12))

    story.append(Paragraph("EXECUTIVE BRIEF (1-MINUTE READ)", h2))
    story.append(Paragraph(f"Detected Domain: {decision.selected_domain}", body))
    story.append(Paragraph(f"Policy Status: {policy.status}", body))

    warning_count = sum(1 for i in insights if i["level"] == "WARNING")
    risk_count = sum(1 for i in insights if i["level"] == "RISK")

    story.append(Paragraph(
        f"Issues Found: {warning_count} Warning(s), {risk_count} Risk(s)",
        body
    ))

    if recommendations:
        story.append(Paragraph(
            f"Immediate Next Step: <b>{recommendations[0].get('action','')}</b>",
            body
        ))

    story.append(Spacer(1, 12))

    # =====================================================
    # EXECUTIVE SNAPSHOT (TABLE)
    # =====================================================

    snapshot_rows = [["Metric", "Value"]]
    for k, v in kpis.items():
        snapshot_rows.append([
            k.replace("_", " ").title(),
            format_kpi(k, v)
        ])

    if len(snapshot_rows) == 1:
        snapshot_rows.append(["KPIs", "Not available"])

    snapshot_table = Table(snapshot_rows, colWidths=[9 * cm, 5 * cm])
    snapshot_table.setStyle(TableStyle([
        ("GRID", (0, 0), (-1, -1), 0.5, "#999999"),
        ("BACKGROUND", (0, 0), (-1, 0), "#EEEEEE"),
    ]))
    story.append(snapshot_table)

    story.append(PageBreak())

    # =====================================================
    # PAGE 2–3 — VISUALS
    # =====================================================

    story.append(Paragraph("Visual Evidence", h1))
    for idx, v in enumerate(visuals[:4]):
        story.append(Image(str(v["path"]), width=14 * cm, height=8 * cm))
        story.append(Paragraph(v.get("caption", ""), body))
        story.append(Spacer(1, 16))
        if idx == 1:
            story.append(PageBreak())

    story.append(PageBreak())

    # =====================================================
    # PAGE 4 — INSIGHTS + RECOMMENDATIONS
    # =====================================================

    story.append(Paragraph("Key Insights", h1))
    for i in insights:
        story.append(Paragraph(
            f"[{i['level']}] {i['title']}",
            body
        ))
        story.append(Paragraph(i.get("so_what", ""), body))
        story.append(Spacer(1, 8))

    story.append(Paragraph("Recommendations", h1))

    for r in recommendations:
        story.append(Paragraph(f"<b>Action:</b> {r.get('action','')}", body))
        story.append(Paragraph(f"Priority: {r.get('priority','Medium')}", body))
        story.append(Paragraph(f"Timeline: {r.get('timeline','TBD')}", body))
        story.append(Paragraph(f"Owner: {r.get('owner','Business Team')}", body))
        story.append(Paragraph(f"Success Metric: {r.get('success_metric','Defined post-approval')}", body))
        story.append(Paragraph(f"Rationale: {r.get('rationale','')}", body))
        story.append(Spacer(1, 10))

    story.append(PageBreak())

    # =====================================================
    # PAGE 5 — RISKS
    # =====================================================

    story.append(Paragraph("Risks", h1))
    risks = [i for i in insights if i["level"] == "RISK"]

    if risks:
        for r in risks:
            story.append(Paragraph(r["title"], body))
            story.append(Paragraph(r.get("so_what", ""), body))
            story.append(Spacer(1, 8))
    else:
        story.append(Paragraph("No critical risks detected.", body))

    doc.build(story, onFirstPage=header_footer, onLaterPages=header_footer)
    return str(output_path)
